// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XInstallBotProfile.Context;

#nullable disable

namespace XInstallBotProfile.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250307213443_CreateTableStatistic")]
    partial class CreateTableStatistic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StatisticTypeUser", b =>
                {
                    b.Property<int>("StatisticTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("StatisticTypesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("StatisticTypeUser");
                });

            modelBuilder.Entity("XInstallBotProfile.Models.StatisticType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("statistic_type", (string)null);
                });

            modelBuilder.Entity("XInstallBotProfile.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDsp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDspBanner")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDspInApp")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtToken")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user_auth_info", (string)null);
                });

            modelBuilder.Entity("XInstallBotProfile.Models.UserStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Ack")
                        .HasColumnType("bigint");

                    b.Property<long>("ClicksCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CompletesCount")
                        .HasColumnType("bigint");

                    b.Property<long>("Ctr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ImpsCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ShowRate")
                        .HasColumnType("numeric");

                    b.Property<long>("StartsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("StatisticTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<long>("Vtr")
                        .HasColumnType("bigint");

                    b.Property<long>("Win")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatisticTypeId");

                    b.ToTable("user_statistic", (string)null);
                });

            modelBuilder.Entity("StatisticTypeUser", b =>
                {
                    b.HasOne("XInstallBotProfile.Models.StatisticType", null)
                        .WithMany()
                        .HasForeignKey("StatisticTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XInstallBotProfile.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XInstallBotProfile.Models.UserStatistic", b =>
                {
                    b.HasOne("XInstallBotProfile.Models.StatisticType", "StatisticType")
                        .WithMany("UserStatistics")
                        .HasForeignKey("StatisticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticType");
                });

            modelBuilder.Entity("XInstallBotProfile.Models.StatisticType", b =>
                {
                    b.Navigation("UserStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
